# Generated by Django 3.2.9 on 2021-11-29 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuKien',
            fields=[
                ('ma_sk', models.AutoField(db_column='MA_SK', primary_key=True, serialize=False)),
                ('ten_sk', models.CharField(db_column='TEN_SK', max_length=50)),
                ('mo_ta', models.CharField(db_column='MO_TA', max_length=200)),
                ('ngay_bd', models.DateTimeField(db_column='NGAY_BD')),
                ('ngay_kt', models.DateTimeField(db_column='NGAY_KT')),
            ],
            options={
                'db_table': 'SU_KIEN',
                'managed': False,
            },
        ),
    ]
