# Generated by Django 3.2.9 on 2022-01-16 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hoadon',
            name='ma_khach_hang',
            field=models.ForeignKey(db_column='MA_KHACH_HANG', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='restaurant_management.khachhang'),
        ),
        migrations.AlterField(
            model_name='hoadon',
            name='ma_nhan_vien',
            field=models.ForeignKey(db_column='MA_NHAN_VIEN', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='restaurant_management.nhanvien'),
        ),
    ]
